### ISSUE TITLE
Some of the questions don't make sense.

### ISSUE THREAD

**Issue by MattSandy** [ReeceGoding/Frustration-One-Year-With-R#2]
>“Why is 1 == "1" true?”

Coercion. When comparing vectors, if there is a character in the vector then everything is compared as a character vector. Same reason `c(1,2,"3")` returns `[1] "1" "2" "3"`

>“Why is -1 < FALSE true?”

Coercion. Booleans are evaluated as numerics (0 and 1) when compared with numerics. Same reason `FALSE == 0` is `TRUE`.

>“Why is "one" < 2 false?”.

Coercion. Imagine sorting something that starts with a number vs something with a letter.

**Comment by ReeceGoding** [comment]
I completely agree that you can make sense of these questions and answer them accurately. Indeed, given that I copied them from *Advanced R*'s exercises, you'd expect that.  However, my point was that the coercion in of itself is capable of tripping you up. To quote the words immediately above those questions: _"One day, you’ll be tripped up by R’s hierarchy of how it likes to simplify mixed types outside of lists."_

I'm happy to re-write the relevant bullet point if you think it's unclear?

**Comment by MattSandy** [comment]
I am a dunce and only saw those questions while skimming.
