### ISSUE TITLE
`combn()`

### ISSUE THREAD

**Issue by kennedymwavu** [ReeceGoding/Frustration-One-Year-With-R#6]
Section `4.12`:
> Despite there being a function for finding the combinations that you can make from the elements of a vector, there’s no function that does that with repetitions. For example, combn(1:3, 2) can’t be convinced to include c(1, 1), c(2, 2), and c(3, 3).

More of a note, not to brush off your claim but I think `expand.grid()` would do something similar to `combn()` with repetitions:

```r
expand.grid(1:3, 1:3)
#>   Var1 Var2
#> 1    1    1
#> 2    2    1
#> 3    3    1
#> 4    1    2
#> 5    2    2
#> 6    3    2
#> 7    1    3
#> 8    2    3
#> 9    3    3
```

**Comment by ReeceGoding** [comment]
The problem with `expand.grid` is that it generates all permutations. For example, you can't tell it that it doesn't need to include both `c(1, 2)` and `c(2, 1)`.

Just to spell it out:
```R
combn(1:3, 2)
#>      [,1] [,2] [,3]
#> [1,]    1    1    2
#> [2,]    2    3    3

expand.grid(1:3, 1:3)
#>   Var1 Var2
#> 1    1    1
#> 2    2    1
#> 3    3    1
#> 4    1    2
#> 5    2    2
#> 6    3    2
#> 7    1    3
#> 8    2    3
#> 9    3    3

whatIWant(1:3, 2)
#>      [,1] [,2] [,3] [,4] [,5] [,6]
#> [1,]    1    1    2    1    2    3
#> [2,]    2    3    3    1    2    3
```
I'll make it more clear in the next version.

**Comment by kennedymwavu** [comment]
Ahaa! Agreed.
