### ISSUE TITLE
Shortcuts in RStudio

### ISSUE THREAD

**Issue by t-wojciech** [ReeceGoding/Frustration-One-Year-With-R#7]
There are very helpful keyboard shortcuts in RStudio (and in other IDEs as well) that I always use.

> Without crude if(FALSE){} workarounds, there’s no way to comment out blocks.

`CTRL` + `SHIFT` + `C` can be used to comment out and uncomment code blocks.

> <- was designed for keyboards that don’t exist any more. It’s a pain to type on a modern system.

`ALT` + `-`

**Comment by ReeceGoding** [comment]
I've always found 'Alt' + '-' harder to type than just '->', but it is nice that it automatically does the spacing. As for the other IDE shortcut, that's absolutely worth a mention. I'll add it in the next version.

**Comment by ReeceGoding** [comment]
Fixed.
