### ISSUE TITLE
Speaking of Lisp

### ISSUE THREAD

**Issue by mdsumner** [ReeceGoding/Frustration-One-Year-With-R#8]
just for Miscellaneous Positives, perhaps worth mentioning this work: https://researchspace.auckland.ac.nz/handle/2292/47321

and the lead-up papers on Ihaka's site: https://www.stat.auckland.ac.nz/~ihaka/?Papers_and_Talks

**Comment by ReeceGoding** [comment]
I think I'm missing your point. As far as I can tell from skimming, those links lead to a PhD thesis that makes up a language spec for a language that's trying to improve on R, but makes little mention of the faults of R itself. I also see few connections to Lisp.

**Comment by mdsumner** [comment]
no problem - Ihaka for years wrote of  a return to Lisp to start afresh, just wanted you to be aware in case you hadn't seen
